delhi_metro = {
    'Huda City Centre': set(['IFFCO Chowk']),
    'IFFCO Chowk': set(['Huda City Centre', 'MG Road']),
    'MG Road': set(['IFFCO Chowk', 'Sikanderpur']),
    'Sikanderpur': set(['MG Road', 'Guru Dronacharya']),
    'Guru Dronacharya': set(['Sikanderpur', 'Arjan Garh']),
    'Arjan Garh': set(['Guru Dronacharya', 'Ghitorni']),
    'Ghitorni': set(['Arjan Garh', 'Sultanpur']),
    'Sultanpur': set(['Ghitorni', 'Chhatarpur']),
    'Chhatarpur': set(['Sultanpur', 'Qutub Minar']),
    'Qutub Minar': set(['Chhatarpur', 'Saket']),
    'Saket': set(['Qutub Minar', 'Malviya Nagar']),
    'Malviya Nagar': set(['Saket', 'Hauz Khas']),
    'Hauz Khas': set(['Malviya Nagar', 'Green Park', 'IIT Delhi', 'RK Puram']),
    'Green Park': set(['Hauz Khas', 'AIIMS']),
    'AIIMS': set(['Green Park', 'INA']),
    'INA': set(['AIIMS', 'Jor Bagh']),
    'Jor Bagh': set(['INA', 'Lodhi Road']),
    'Lodhi Road': set(['Jor Bagh', 'Khan Market']),
    'Khan Market': set(['Lodhi Road', 'Central Secretariat']),
    'Central Secretariat': set(['Khan Market', 'Patel Chowk', 'Udyog Bhawan']),
    'Patel Chowk': set(['Central Secretariat', 'Rajiv Chowk']),
    'Rajiv Chowk': set(['Patel Chowk', 'New Delhi', 'Barakhamba']),
    'New Delhi': set(['Rajiv Chowk', 'Chawri Bazar']),
    'Chawri Bazar': set(['New Delhi', 'Chandni Chowk']),
    'Chandni Chowk': set(['Chawri Bazar', 'Kashmere Gate']),
    'Kashmere Gate': set(['Chandni Chowk', 'Civil Lines']),
    'Civil Lines': set(['Kashmere Gate', 'Vidhan Sabha']),
    'Vidhan Sabha': set(['Civil Lines', 'Vishwavidyalaya']),
    'Vishwavidyalaya': set(['Vidhan Sabha', 'GTB Nagar']),
    'GTB Nagar': set(['Vishwavidyalaya', 'Model Town']),
    'Model Town': set(['GTB Nagar', 'Azadpur']),
    'Azadpur': set(['Model Town', 'Adarsh Nagar']),
    'Adarsh Nagar': set(['Azadpur', 'Jahangirpuri']),
    'Jahangirpuri': set(['Adarsh Nagar', 'Samaypur Badli']),
    'RK Puram': set(['IIT Delhi', 'Hauz Khas']),
    'IIT Delhi': set(['RK Puram', 'Hauz Khas']),
    'Nehru Place': set(['Kalkaji Mandir']),
    'Kalkaji Mandir': set(['Nehru Place', 'Lotus Temple']),
    'Lotus Temple': set(['Kalkaji Mandir']),
    'Lajpat Nagar': set(['INA', 'Moolchand']),
    'Moolchand': set(['Lajpat Nagar', 'Kailash Colony']),
    'Kailash Colony': set(['Moolchand', 'Nehru Place']),
    'Tughlaqabad': set(['Nehru Place']),
    'Akshardham': set(['Yamuna Bank']),
    'Yamuna Bank': set(['Akshardham', 'Indraprastha']),
    'Indraprastha': set(['Yamuna Bank', 'Pragati Maidan']),
    'Pragati Maidan': set(['Indraprastha', 'Mandi House']),
    'Mandi House': set(['Pragati Maidan', 'Janpath']),
    'Janpath': set(['Mandi House', 'Rajiv Chowk']),
    'Barakhamba': set(['Rajiv Chowk', 'Mandi House']),
    'Udyog Bhawan': set(['Central Secretariat']),
    'Samaypur Badli': set(['Jahangirpuri']),
}

