landmark_choices = {
    'a': 'India Gate',
    'b': 'Red Fort',
    'c': 'Qutub Minar',
    'd': 'Lotus Temple',
    'e': 'Humayun\'s Tomb',
    'f': 'Akshardham Temple',
    'g': 'Rashtrapati Bhavan',
    'h': 'Connaught Place',
    'i': 'Lodhi Gardens',
    'j': 'Jama Masjid',
    'k': 'Raj Ghat',
    'l': 'National Museum',
    'm': 'Nehru Place',
    'n': 'Chandni Chowk Market',
    'o': 'Dilli Haat',
    'p': 'Lajpat Nagar Market',
    'q': 'Saket Mall',
    'r': 'Cyber Hub',
    's': 'Select Citywalk',
    't': 'Vishwa Vidyalaya (DU North Campus)',
    'u': 'Tughlaqabad Fort'
}
